Installment/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from Installment import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    # the main ressource
    path('', include('accounts.urls', namespace='accounts')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('family/', include('family.urls', namespace='family')),
    path('category/', include('category.urls', namespace='category')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('product/', include('product.urls', namespace='product')),
    path('buyorder/', include('buyorder.urls', namespace='buyorder')),
    path('sellorder/', include('sellorder.urls', namespace='sellorder')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('billingbuyorder/', include('billingbuyorder.urls', namespace='billingbuyorder')),
    path('batch/', include('batch.urls', namespace='batch')),
    path('payments/', include('payments.urls', namespace='payments')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

batch/urls.py
from django.urls import path
from . import views

app_name = 'batch'

urlpatterns = [

    path('create_batch/<str:pk>', views.create_batch, name='create_batch'),
    path('batch_list', views.batch_list, name='batch_list'),
    path('batch_pay/<str:pk>', views.batch_pay, name='batch_pay'),

]

category/urls.py
from django.urls import path
from . import views

app_name = 'category'

urlpatterns = [

    path('all_category_list/', views.all_category_list, name='all_category_list'),
    path('category_list/<str:pk>', views.category_list, name='category_list'),
    path('add_category', views.add_category, name='add_category'),
    path('update_category/<str:pk>', views.update_category, name='update_category'),
    path('delete_category/<str:pk>', views.delete_category, name='delete_category'),

]

family/urls.py
from django.urls import path
from . import views

app_name = 'family'

urlpatterns = [

    path('family_list', views.family_list, name='family_list'),
    path('add_family', views.add_family, name='add_family'),
    path('update_family/<str:pk>', views.update_family, name='update_family'),
    path('delete_family/<str:pk>', views.delete_family, name='delete_family'),

]

category/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.
from family.models import Family


class Category(models.Model):
    family = models.ForeignKey(Family, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, null=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True, )

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    # auto fill the slug when saving
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        # if self.image:
        #    self.image = get_thumbnail(self.image, '570x320').url
        super(Category, self).save(*args, **kwargs)

    # def get_absolute_url(self):
        # TODO : Change it to the new url stock
        # return reverse('warehouse:stockproductcategory_list', args=[self.id])

category/forms.py
from django.forms import ModelForm
from django import forms

from category.models import Category
from family.models import Family


class CategoryForm(ModelForm):
    class Meta:
        model = Category

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name...'}),
            'family': forms.Select(attrs={'class': 'form-control '}),
            'image': forms.FileInput(attrs={'class': 'form-control-file', 'placeholder': 'Image...'}),

        }

        fields = ['family', 'name', 'image', ]

category/views.py
from django.shortcuts import render, redirect

# Create your views here.
from category.forms import CategoryForm
from category.models import Category
from customer.models import Customer
from family.models import Family


def add_category(request):
    if request.method == 'GET':
        categoryform = CategoryForm()
    elif request.method == 'POST':
        categoryform = CategoryForm(request.POST, request.FILES)
        if categoryform.is_valid():
            categoryform.save()
            return redirect('/')
    context = {'categoryform': categoryform}
    return render(request, 'category/add_category.html', context)


def category_list(request, pk):
    family = Family.objects.get(id=pk)
    families = Family.objects.all()
    categories = Category.objects.all().filter(family=family)

    context = {
        'family': family,
        'families': families,
        'categories': categories,
    }
    return render(request, 'category/list_category.html', context)


def all_category_list(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'category/all_list_category.html', context)


def update_category(request, pk):
    category = Category.objects.get(id=pk)
    categoryform = CategoryForm(instance=category)
    if request.method == 'POST':
        categoryform = CategoryForm(request.POST, request.FILES, instance=category)
        if categoryform.is_valid():
            categoryform.save()
            return redirect('/')
    context = {'categoryform': categoryform}
    return render(request, 'category/add_category.html', context)


def delete_category(request, pk):
    category = Category.objects.get(id=pk)
    context = {'category': category}
    if request.method == 'POST':
        category.delete()

        return redirect('/')
    return render(request, 'category/delete_category.html', context)

category/templates/category/add_category.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<br>

    <div class="row">
    <div class="col-md-3 col-sm-1">

    </div>
    <div class="col-md-6 col-sm-12">
        <div class="card card-body">

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{categoryform.as_p}}
                <input class="btn btn-primary" type="submit" name="submit">
            </form>
        </div>
        {% if categoryform.errors %}
        {% for field in categoryform %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{field.label}} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in categoryform.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}


    </div>
    <div class="col-md-3 col-sm-1">

    </div>
</div>

<script>

	</script>
{% endblock %}

category/templates/category/all_list_category.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<br>

<div class="container">
    <div class="row">

        <div class="col-sm-12 col-md-10 col-lg-10">
            <div class="row">
                {% for cat in categories %}
                <div class="col-lg-4 mb-5">
                    <a href="">
                        <div class="card family-card bg-dark text-white" style="width: 18rem; height: 18rem;">
                            <img class="card-img" style="width: 100%; height: 100%;" src="{{cat.image.url}}"
                                 alt="{{cat.name}}">
                            <div class="card-img-overlay">
                                <h4 class="card-title text-center">{{cat.name}}</h4>
                            </div>
                        </div>
                    </a>

                   <a class="btn btn-success " href="{% url 'category:update_category' cat.id %}">Update</a>
                   <a class="btn btn-danger " href="{% url 'category:delete_category' cat.id %}">Delete</a>

                </div>
                {% endfor %}
            </div>
        </div>

    </div>

</div>

{% endblock %}

category/templates/category/delete_category.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<br>

<div class="container">
    <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="card card-body">
            <P>ARE YOU SURE YOU WANT TO DELETE {{category}}</P>
            <form action="{% url 'category:delete_category' category.id %}" method="post">

                {% csrf_token %}
                <input class="btn btn-danger" type="submit" name="Confirm">
                <a class="btn btn-warning" href="{% url 'family:family_list' %}">Cancel</a>
            </form>
        </div>
    </div>
    <div class="col-md-3">
    </div>
</div>
</div>


<script>

</script>
{% endblock %}

category/templates/category/list_category.html
{% extends 'home.html' %}
{% load static %}

{% block content %}

<br>

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-3">
            <h3>Families</h3>
            <div class="list-group">
                {% for f in families %}
                <a {% if family == f %}
                        class=" list-group-item list-group-item-action active"
                       {% else %}
                       class="list-group-item list-group-item-action"
                       {% endif %}
                        href="{{f.get_absolute_url}}">
                    {{f.name}}
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-sm-12 col-md-9 col-lg-9">
            <div class="row">
                {% for cat in categories %}
                <div class="col-lg-4 mb-5">
                    <a href="">
                        <div class="card family-card bg-dark text-white" style="width: 18rem; height: 18rem;">
                            <img class="card-img" style="width: 100%; height: 100%;" src="{{cat.image.url}}"
                                 alt="{{cat.name}}">
                            <div class="card-img-overlay">
                                <h4 class="card-title text-center">{{cat.name}}</h4>
                            </div>
                        </div>
                    </a>


                </div>
                {% endfor %}
            </div>
        </div>

    </div>

</div>
<script>

</script>
{% endblock %}