Installment/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from Installment import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    # the main ressource
    path('', include('accounts.urls', namespace='accounts')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('family/', include('family.urls', namespace='family')),
    path('category/', include('category.urls', namespace='category')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('product/', include('product.urls', namespace='product')),
    path('buyorder/', include('buyorder.urls', namespace='buyorder')),
    path('sellorder/', include('sellorder.urls', namespace='sellorder')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('billingbuyorder/', include('billingbuyorder.urls', namespace='billingbuyorder')),
    path('batch/', include('batch.urls', namespace='batch')),
    path('payments/', include('payments.urls', namespace='payments')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

batch/urls.py
from django.urls import path
from . import views

app_name = 'batch'

urlpatterns = [

    path('create_batch/<str:pk>', views.create_batch, name='create_batch'),
    path('batch_list', views.batch_list, name='batch_list'),
    path('batch_pay/<str:pk>', views.batch_pay, name='batch_pay'),

]

buyorder/urls.py
from django.urls import path
from . import views

app_name = 'buyorder'

urlpatterns = [

    path('create_buyorder', views.create_buyorder, name='create_buyorder'),
    path('buyorder_list', views.buyorder_list, name='buyorder_list'),
    path('buyorder_confirmation/<str:pk>', views.buyorder_confirmation, name='buyorder_confirmation'),
    path('buyorder_pdf/<str:pk>', views.buyorder_pdf, name='buyorder_pdf'),
    path('buyorderorder_list_by_supplier/<str:pk>', views.buyorderorder_list_by_supplier, name='buyorderorder_list_by_supplier'),

]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stocking'

urlpatterns = [

    path('add_stock', views.add_stock, name='add_stock'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('all_stock_list', views.all_stock_list, name='all_stock_list'),
    path('update_stock/<str:pk>', views.update_stock, name='update_stock'),
    path('delete_stock/<str:pk>', views.delete_stock, name='delete_stock'),

    path('add_stockproduct', views.add_stockproduct, name='add_stockproduct'),
    path('stockproduct_list/<str:pk>', views.stockproduct_list, name='stockproduct_list'),
    path('all_stockproduct_list', views.all_stockproduct_list, name='all_stockproduct_list'),
    path('order_stockproduct_list', views.order_stockproduct_list, name='order_stockproduct_list'),
    path('update_stockproduct/<str:pk>', views.update_stockproduct, name='update_stockproduct'),
    path('delete_stockproduct/<str:pk>', views.delete_stockproduct, name='delete_stockproduct'),
    path('stockproductcategory_list/<str:pk>', views.stockproductcategory_list, name='stockproductcategory_list'),
    path('stockproduct_detail/<str:id>', views.stockproduct_detail, name='stockproduct_detail'),
    path('stockproduct_stockalert', views.stockproduct_quantityalert, name='stockproduct_stockalert'),
    # path('autocomplete_product', views.productautocomplete, name='autocomplete_product'),
    # path('autocomplete_product', views.CompleteProduct.as_view, name='autocomplete_product'),
    path('ajax/load-types/', views.loadtypes, name='ajax_load_types'),
    path('ajax/load-colors/', views.loadcolors, name='ajax_load_colors'),
    path('ajax/load-price/', views.loadprice, name='ajax_load_price'),

]

buyorder/forms.py
from django.forms import ModelForm, modelformset_factory
from buyorder.models import BuyOrder, BuyOrderItem
from product.models import ProductType, ProductColor, Product
from django import forms
from dal import autocomplete


class BuyOrderForm(ModelForm):
    class Meta:
        model = BuyOrder

        fields = ['supplier', ]


# create a form and put it in a formset so you can control some fields property and init the form
class BuyOrderItemForm(forms.ModelForm):
    class Meta:
        model = BuyOrderItem
        product = forms.ModelChoiceField(queryset=Product.objects.all(),
                                         widget=autocomplete.ModelSelect2(url='autocomplete_product'))
        widgets = {
            'product': forms.Select(attrs={'class': 'chosen form-control'}),
            # forms.TextInput(attrs={'class': 'form-control product_name'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'color': forms.Select(attrs={'class': 'form-control'}),
        }

        fields = ['product', 'quantity', 'price', 'type', 'color']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['type'].queryset = ProductType.objects.none()
        self.fields['color'].queryset = ProductColor.objects.none()

        # if the user hit submit but didn't choose a color & type we fill it directly from product field
        if 'product' in self.data:
            try:
                requestproduct = int(self.data.get('product'))
                splitedproduct = requestproduct.split()
                product = Product.objects.get(id=splitedproduct[0])
                self.fields['type'].queryset = ProductType.objects.filter(product=product).order_by('name')
                self.fields['color'].queryset = ProductColor.objects.filter(product=product).order_by('name')
                self.fields['price'].queryset = product.buyprice
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
        #     self.fields['city'].queryset = self.instance.country.city_set.order_by('name')


BuyOrderItemFormset = modelformset_factory(
    BuyOrderItem,
    form=BuyOrderItemForm,
    extra=1,
)

buyorder/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string

from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
# Create your views here.
from billingbuyorder.models import BuyOrderBilling, BillBuyOrderItem
from buyorder.forms import BuyOrderForm, BuyOrderItemFormset
from buyorder.models import BuyOrderItem, BuyOrder
from product.models import Product, ProductColor, ProductType
from supplier.models import Supplier
from stock.models import StockProduct


def create_buyorder(request):
    buyorderform = BuyOrderForm()
    buyorderitemformset = BuyOrderItemFormset(queryset=BuyOrderItem.objects.none())

    products = Product.objects.all()

    if request.method == 'POST':
        # print(request.POST)
        # fix the form to be validated
        # get the list of the chosen products
        products_list = request.POST.getlist('products')
        # print(products_list)
        buyorderform = BuyOrderForm(request.POST)
        # if the list has elements

        if buyorderform.is_valid():
            if len(products_list):
                buyorder = buyorderform.save()
                # to add credit
                # supplier = Supplier.objects.get(id=request.POST['supplier'])
                buyorder.user = request.user.id
                for prod_list_item in products_list:
                    # saving the order items
                    orderitem = BuyOrderItem()
                    orderitem.order = buyorder
                    orderitem.product = Product.objects.get(id=prod_list_item)
                    orderitem.price = Product.objects.get(id=prod_list_item).buyprice
                    orderitem.save()
                    # print(Product.objects.get(id=prod_list_item))

            return redirect(f'../buyorder/buyorder_confirmation/{buyorder.pk}')
    context = {
        'products': products,
        'buyorderform': buyorderform,
        'buyorderitemformset': buyorderitemformset
    }
    return render(request, 'buyorder/add_buyorder.html', context)


def buyorder_confirmation(request, pk):
    buyorder = BuyOrder.objects.get(id=pk)

    buyorderform = BuyOrderForm(instance=buyorder)
    if request.method == 'POST':
        buyorderform = BuyOrderForm(request.POST, instance=buyorder)
        if buyorderform.is_valid():
            print(request.POST)

            buyorder = buyorderform.save()
            # to add credit
            supplier = Supplier.objects.get(id=request.POST['supplier'])
            # get modified items
            prices = request.POST.getlist('prices')
            quantities = request.POST.getlist('quantities')
            colors = request.POST.getlist('color')
            types = request.POST.getlist('type')
            for index, item in enumerate(buyorder.items.all()):
                # print(index, item)
                print(prices[index], quantities[index], colors[index], types[index])
                # get the price and value of each element
                # Saving the orderitem
                item.price = prices[index]
                item.quantity = quantities[index]
                if colors[index] != "None":
                    item.color = ProductColor.objects.get(id=colors[index])
                if types[index] != "None":
                    item.type = ProductType.objects.get(id=types[index])
                item.save()
                # adding the bought products to stock
                stockitems = StockProduct.objects.all().filter(stock=item.product.stock)
                itemexist = 1
                #     # check if stock doesn't have the product
                # if len(stockitems) > 0:
                #     # stock has products check if product exist
                #     for stockitem in stockitems:
                #         # the same product exist
                #         if stockitem.product.id == item.product.id:
                #             stockitem.quantity += int(item.quantity)
                #             stockitem.save()
                #             itemexist = 2
                #             #                 # operation done same product plus the new quantity
                #
                #     if itemexist == 1:
                #         #             # stock not empty product doesn't exist in it
                #         #             # create new stockproduct
                #         StockProduct.objects.create(
                #             product=item.product,
                #             quantity=int(item.quantity),
                #             type=item.type,
                #             color=item.color,
                #             category=item.product.category,
                #             stock=item.product.stock
                #         )
                # else:
                #     #         # stock is empty
                #     itemexist = 0
                #     if itemexist == 0:
                #         # create new stockproduct
                #         StockProduct.objects.create(
                #             product=item.product,
                #             quantity=int(item.quantity),
                #             type=item.type,
                #             color=item.color,
                #             category=item.product.category,
                #             stock=item.product.stock
                #         )
            print(buyorder.get_total_cost())
            print(supplier)
            # supplier.credit += buyorder.get_total_cost()
            # supplier.save()
            return redirect('buyorder:buyorder_list')
    context = {
        'buyorderform': buyorderform,
        'buyorder': buyorder,
    }
    return render(request, 'buyorder/buyorder_confirmation.html', context)


def buyorder_list(request):
    buyorders = BuyOrder.objects.all()
    context = {
        'buyorders': buyorders
    }
    return render(request, 'buyorder/list_buyorder.html', context)


def buyorderorder_list_by_supplier(request, pk):
    supplier = Supplier.objects.get(id=pk)
    buyorders = BuyOrder.objects.all().filter(supplier=supplier, factured=False)

    if request.method == 'POST':
        # get submitted orders
        chosenorders = request.POST.getlist("orders")
        # create billing object if there is selected orders
        if len(chosenorders) != 0:
            # print(chosenorders)
            # buyorderbill object
            buyorderbilling = BuyOrderBilling()
            buyorderbilling.supplier = supplier
            # TODO : Uncomment this line
            # buyorderbilling.user = request.user.id
            buyorderbilling.save()
            for orderid in chosenorders:
                # each order is a billing item
                currentorder = BuyOrder.objects.get(id=orderid)
                currentorder.factured = True
                currentorder.save()
                orderprice = currentorder.get_total_cost()
                # adding supplier credit
                supplier.credit += orderprice
                supplier.save()
                #                orderweight = currentorder.get_total_weight()
                BillBuyOrderItem.objects.create(
                    bill=buyorderbilling,
                    order=currentorder,
                    price=orderprice,
                    #                   weight=orderweight,
                )
                # reduce quantity from the stock
                currentorderitems = currentorder.items.all()
                for item in currentorderitems:
                    stockitems = StockProduct.objects.all().filter(stock=item.product.stock)
                    itemexist = 1
                    # check if stock doesn't have the product
                    if len(stockitems) > 0:
                        # stock has products check if product exist
                        for stockitem in stockitems:
                            # the same product exist
                            if stockitem.product.id == item.product.id:
                                stockitem.quantity += int(item.quantity)
                                stockitem.save()
                                itemexist = 2
                                #                 # operation done same product plus the new quantity

                        if itemexist == 1:
                            #             # stock not empty product doesn't exist in it
                            #             # create new stockproduct
                            StockProduct.objects.create(
                                product=item.product,
                                quantity=int(item.quantity),
                                type=item.type,
                                color=item.color,
                                category=item.product.category,
                                stock=item.product.stock
                            )
                    else:
                        #         # stock is empty
                        itemexist = 0
                        if itemexist == 0:
                            # create new stockproduct
                            StockProduct.objects.create(
                                product=item.product,
                                quantity=int(item.quantity),
                                type=item.type,
                                color=item.color,
                                category=item.product.category,
                                stock=item.product.stock
                            )
            # send bill to be printed
            pk = buyorderbilling.pk
            return redirect(f'../../billingbuyorder/bill_pdf/{pk}')

    context = {
        'buyorders': buyorders
    }
    return render(request, 'buyorder/billing_list_buyorder.html', context)


def buyorder_pdf(request, pk):
    buyorder = get_object_or_404(BuyOrder, id=pk)

buyorder/templates/buyorder/add_buyorder.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<br>

<div class="row">
    <div class="col-md-2 col-sm-1"></div>
    <div class="col-md-10 col-sm-12">
        <div class="card card-body">
            <h5 class="text-center">Create Order</h5>
            <form id="buyorderform" action="" method="post" data-types-url="{% url 'stock:ajax_load_types' %}"
                data-colors-url="{% url 'stock:ajax_load_colors' %}"
                data-price-url="{% url 'stock:ajax_load_price' %}" novalidate>

                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <div class="">
                            {{buyorderform|crispy}}
                        </div>
                    </div>
                </div>
                <br>
                <hr>

                <table id="table_id" class="display text-center">
                    <thead>
                    <tr>
                        <th><label class="form-check-label" for="{{product.id}}"/></th>
                        <th>Name</th>
                        <th>Ref</th>
                        <th>Price DZD</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for product in products %}
                    <tr>
                        <td><input class="form-check-input" type="checkbox" value="{{product.id}}" id="{{product.id}}" name="products">
                        </td>
                        <td class="h6">{{product.name}}</td>
                        <td class="h6">{{product.ref}}</td>
                        <td class="h6">
                            {{product.buyprice}}
                        </td>

                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <hr>
                <br>
                <div class="row spacer">
                    <div class="col-4 offset-2">
                        <input class="btn btn-primary" type="submit" name="submit">
                    </div>
                </div>
            </form>
        </div>

        {% for error in buyorderform.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-2 col-sm-1"></div>
</div>

{% endblock %}
{% block jsscript %}
<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>
<!-- Data Table  -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>

<script type='text/javascript'>
    //Data Table init
    $(document).ready( function () {
    $('#table_id').DataTable();
} );

    maxnum = 0

    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }

    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        //  var inputs = $('input, textarea, select')
        //      .not(':input[type=button], :input[type=submit], :input[type=reset]');
        //  $(inputs).each(function () {
        //      console.log(this.type);
        // });

        //  newElement = $('input').not(':input[type=button], :input[type=submit], :input[type=reset]');
        // $(newElement).each(function () {


        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
            if ($(this).attr('name')) {
                var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({
                    'name': name,
                    'id': id
                }).val('').removeAttr('checked');
            }
            // var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
            // var id = 'id_' + name;
            // $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({
                    'for': forValue
                });
            }
        });
        total++;
        maxnum = total
        // alert(maxnum);
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        var conditionRow = $('.form-row:not(:last)');
        conditionRow.find('.btn.add-form-row')
            .removeClass('btn-success').addClass('btn-danger')
            .removeClass('add-form-row').addClass('remove-form-row')
            .html('<span class="glyphicon glyphicon-minus" aria-hidden="true"><i class="fas fa-minus"></i></span>');
        return false;
    }

    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }
    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        fillitems();
        return false;
    });
    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        fillitems();
        return false;
    });

    // filling all the inputs in an array then assign fillitems to them
    function fillitems() {
        var inputs = document.querySelectorAll('select');
        for (var i = 0; i < inputs.length; ++i) {
            //alert("items filled "+inputs[i].id)
           // inputs[i].addEventListener('input', suggestions);
          // inputs[i].addEventListener('input', add_chosen);
           full_id = inputs[i].id;
           str = full_id.toString();
           strarray = str.split("-");
           //alert(strarray[strarray.length - 1]);
           //alert(full_id);
           console.log(full_id)
           if (strarray[strarray.length - 1] === "product") {
           $("#" + full_id).chosen();
           console.log("Chosen"+full_id);
           }
        }
    }

    // add the first element
    $(function () {
        fillitems();
    });

    function add_chosen(){
       // alert(this.id)
        full_id = this.id;
        str = full_id.toString();
        strarray = str.split("-");
        //alert(strarray[strarray.length - 1]);
        //alert(full_id);
        console.log(full_id)
        if (strarray[strarray.length - 1] === "product") {
            $("#" + full_id).chosen();
            console.log("Chosen"+full_id);
        }
    }

</script>
{% endblock %}

buyorder/templates/buyorder/billing_list_buyorder.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Orders</h5>
        </div>
        <div class="card card-body">
            <form action="" method="post">
                {% csrf_token %}
                <table class="table">
                    {% for order in buyorders %}

                    <thead>
                    <tr>
                        <th>
                            <label class="form-check-label" for="{{order.id}}"/>
                        </th>
                        <th>Order ID</th>
                        <th>Total Price</th>
                        <th>Total Weight</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><input class="form-check-input" type="checkbox" value="{{order.id}}" id="{{order.id}}" name="orders">
                        </td>
                        <td>{{order.id}}</td>
                        <td>DZD {{order.get_total_cost}}</td>
                        <td>KG {{order.get_total_weight}}</td>
                        <td>
                            <a class="btn btn-warning " href="{% url 'buyorder:buyorder_pdf' order.id %}">Print</a>
                        </td>
                    </tr>

                    <thead class="thead-light">
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total Cost</th>
                        <th>Total Weight</th>
                        <th></th>
                    </tr>
                    </thead>

                    {% for item in order.items.all %}
                    <tr>
                        <td class="table-light"></td>
                        <td class="table-light"></td>
                        <td class="table-light">{{ item.product.name }}</td>
                        <td class="table-light ">DZD{{ item.price }}</td>
                        <td class="table-light ">{{ item.quantity }}</td>
                        <td class="table-light">DZD{{ item.get_cost }}</td>
                        <td class="table-light">KG {{ item.get_weight }}</td>
                        <td class="table-light"></td>
                    </tr>
                    {% endfor %}

                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>

                    </tbody>

                    {% endfor %}
                    <tr class="text-center">
                        <td class="text-center">
                                                    <input class="btn btn-primary" type="submit" name="submit">

                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

{% endblock %}

buyorder/templates/buyorder/buyorder_confirmation.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Orders</h5>
        </div>
        <div class="card card-body">
            <form action="" method="post">
                {% csrf_token %}
                                            {{buyorderform|crispy}}
                <hr>
                <br>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Supplier</th>
                        <th>City</th>
                        <th>Paid</th>
                        <th>Total Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{{buyorder.id}}</td>
                        <td>{{buyorder.supplier}}</td>
                        <td>{{buyorder.supplier.city}}</td>
                        <td>{{buyorder.paid}}</td>
                        <td>DZD {{buyorder.get_total_cost}}</td>
                    </tr>

                    <thead class="thead-light">
                    <tr>

                        <th>Product Name</th>
                        <th>Price DZD</th>
                        <th>Quantity</th>
                        <th>Color</th>
                        <th>Type</th>
                    </tr>
                    </thead>

                    {% for item in buyorder.items.all %}
                    <tr>

                        <td class="table-light" >
                            <input class="form-control" type="text" value="{{ item.product.name }}" name="names" disabled>
                            </td>
                        <td class="table-light ">
                            <input class="form-control" type="number" name="prices" value="{{ item.price }}">

                        </td>
                        <td class="table-light ">
                            <input class="form-control" type="number" name="quantities" value="{{ item.quantity }}">
                            </td>
                        <td class="table-light">
                            <select class="form-control" name="color">
                                {% for color in item.product.get_colors %}
                                <option value="{{color.id}}">{{color}}</option>
                                {% empty %}
                                <option value="None">None</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td class="table-light">
                            <select class="form-control" name="type">

                                {% for type in item.product.get_types %}

                                <option value="{{type.id}}">{{type}}</option>
                                {% empty %}
                                <option value="None">None</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                    {% endfor %}

                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>

                    </tbody>

                    <tr class="text-center">
                        <td class="text-center">
                                                    <input class="btn btn-primary" type="submit" name="submit">

                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

{% endblock %}