Installment/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from Installment import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    # the main ressource
    path('', include('accounts.urls', namespace='accounts')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('family/', include('family.urls', namespace='family')),
    path('category/', include('category.urls', namespace='category')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('product/', include('product.urls', namespace='product')),
    path('buyorder/', include('buyorder.urls', namespace='buyorder')),
    path('sellorder/', include('sellorder.urls', namespace='sellorder')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('billingbuyorder/', include('billingbuyorder.urls', namespace='billingbuyorder')),
    path('batch/', include('batch.urls', namespace='batch')),
    path('payments/', include('payments.urls', namespace='payments')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

batch/urls.py
from django.urls import path
from . import views

app_name = 'batch'

urlpatterns = [

    path('create_batch/<str:pk>', views.create_batch, name='create_batch'),
    path('batch_list', views.batch_list, name='batch_list'),
    path('batch_pay/<str:pk>', views.batch_pay, name='batch_pay'),

]

family/urls.py
from django.urls import path
from . import views

app_name = 'family'

urlpatterns = [

    path('family_list', views.family_list, name='family_list'),
    path('add_family', views.add_family, name='add_family'),
    path('update_family/<str:pk>', views.update_family, name='update_family'),
    path('delete_family/<str:pk>', views.delete_family, name='delete_family'),

]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('all_product_list/', views.all_product_list, name='all_product_list'),
    path('product_list/<str:pk>', views.product_list, name='product_list'),
    path('add_product', views.add_product, name='add_product'),
    path('update_product/<str:pk>', views.update_product, name='update_product'),
    path('delete_product/<str:pk>', views.delete_product, name='delete_product'),

    path('add_product_type/<str:pk>', views.add_type, name='add_product_type'),

    path('add_product_color/<str:pk>', views.add_color, name='add_product_color'),


]

product/models.py
from django.db import models

# Create your models here.

from category.models import Category


class Product(models.Model):
    # add buy price or production price
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, null=True)
    ref = models.CharField(max_length=250, null=True)
    desc = models.CharField(max_length=250, null=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, )
    buyprice = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    sellpricenormal = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    # sellpricesemi_grou = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    # sellpricegrou = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    # sellspecialprice = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0)
    weight = models.DecimalField(max_digits=10, null=True, decimal_places=2, default=0.0)
    # alert_quantity = models.PositiveIntegerField(default=1)
    # box_quantity = models.PositiveIntegerField(default=1)
    stock = models.ForeignKey('stock.Stock', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

    def have_types(self):
        return self.types.all().count()

    def have_colors(self):
        return self.colors.all().count()

    def get_types(self):
        return self.types.all().filter(product=self)

    def get_colors(self):
        return self.colors.all().filter(product=self)


class ProductType(models.Model):
    product = models.ForeignKey(Product,
                                related_name='types',
                                on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=250, null=True)

    def __str__(self):
        return self.name


class ProductColor(models.Model):
    product = models.ForeignKey(Product,
                                related_name='colors',
                                on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=250, null=True)

    def __str__(self):
        return self.name

product/forms.py
from django.forms import ModelForm, modelformset_factory
from django import forms
from product.models import Product, ProductType, ProductColor


class ProductForm(ModelForm):
    class Meta:
        model = Product

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name...'}),
            'ref': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'REF...'}),
            'desc': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Desc...'}),
            'category': forms.Select(attrs={'class': 'form-control '}),
            'stock': forms.Select(attrs={'class': 'form-control '}),
            'image': forms.FileInput(attrs={'class': 'form-control-file', 'placeholder': 'Image...'}),
            'sellpricenormal': forms.NumberInput(attrs={'class': 'form-control '}),
            # 'sellpricesemi_grou': forms.NumberInput(attrs={'class': 'form-control '}),
            # 'sellpricegrou': forms.NumberInput(attrs={'class': 'form-control '}),
            'buyprice': forms.NumberInput(attrs={'class': 'form-control '}),
            # 'alert_quantity': forms.NumberInput(attrs={'class': 'form-control '}),
            # 'box_quantity': forms.NumberInput(attrs={'class': 'form-control '}),
            'weight': forms.NumberInput(attrs={'class': 'form-control '}),

        }

        fields = ['category', 'name', 'ref', 'desc', 'image', 'stock', 'sellpricenormal',
                  'buyprice', 'weight']


ProductTypeFormset = modelformset_factory(
    ProductType,
    fields=('name', ),
    extra=1,
)


ProductColorFormset = modelformset_factory(
    ProductColor,
    fields=('name',),
    extra=1,
)

product/views.py
from django.shortcuts import render, redirect

# Create your views here.
from category.models import Category
from product.forms import ProductForm, ProductTypeFormset, ProductColorFormset
from product.models import Product, ProductType, ProductColor


def add_product(request):
    if request.method == 'GET':
        productform = ProductForm()
    elif request.method == 'POST':
        productform = ProductForm(request.POST, request.FILES)
        if productform.is_valid():
            product = productform.save()
            return redirect(f'../product/add_product_type/{product.pk}')
    context = {'productform': productform}
    return render(request, 'product/add_product.html', context)


def product_list(request, pk):
    category = Category.objects.get(id=pk)
    products = Product.objects.all().filter(category=category)
    context = {
        'products': products,
    }
    return render(request, 'product/list_product.html', context)


def all_product_list(request):
    products = Product.objects.all()
    context = {
        'products': products,
    }
    return render(request, 'product/all_product_list.html', context)


def update_product(request, pk):
    product = Product.objects.get(id=pk)
    productform = ProductForm(instance=product)
    if request.method == 'POST':
        productform = ProductForm(request.POST, request.FILES, instance=product)
        if productform.is_valid():
            productform.save()
            return redirect('/')
    context = {'productform': productform}
    return render(request, 'product/add_product.html', context)


def delete_product(request, pk):
    product = Product.objects.get(id=pk)
    context = {'product': product}
    if request.method == 'POST':
        product.delete()
        return redirect('/')
    return render(request, 'product/delete.html', context)


def add_type(request, pk):
    product = Product.objects.get(id=pk)
    productypeformset = ProductTypeFormset(queryset=ProductType.objects.none())
    if request.method == 'POST':
        productypeformset = ProductTypeFormset(request.POST)
        if productypeformset.is_valid():
            for typeform in productypeformset:
                producttype = typeform.save(commit=False)
                producttype.product = product
                producttype.save()

            return redirect(f'../add_product_color/{product.pk}')
    context = {
        'productypeformset': productypeformset,
    }
    return render(request, 'product/add_type.html', context)


def add_color(request, pk):
    product = Product.objects.get(id=pk)
    productcolorformset = ProductColorFormset(queryset=ProductColor.objects.none())
    if request.method == 'POST':
        productcolorformset = ProductColorFormset(request.POST)
        if productcolorformset.is_valid():
            for colorform in productcolorformset:
                productcolor = colorform.save(commit=False)
                productcolor.product = product
                productcolor.save()

            return redirect('/')
    context = {
        'productcolorformset': productcolorformset,
    }
    return render(request, 'product/add_color.html', context)

product/templates/product/add_color.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
        <div class="col-md-2 col-sm-1"></div>

    <div class="col-md-10 col-sm-12">
        <div class="card card-body">
            <h5 class="text-center">Create Product Color</h5>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{ productcolorformset.management_form }}
            {% for form in productcolorformset %}
                <div class="row form-row spacer">
                    <div class="col-2">
                    </div>
                    <div class="col-9">
                        <div class="input-group">
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            <p class="hidden">{{ form.id }}</p>
                            {{form|crispy}}
                            <div class="input-group-append">
                                <button class="btn btn-success add-form-row">+</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <br>
            <div class="row spacer">
                    <div class="col-4 offset-2">
                        <input class="btn btn-primary" type="submit" name="submit">
                    </div>
                </div>
        </form>
    </div>
    {% if productcolorformset.errors %}
        {% for form in productcolorformset %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{field.label}} {{field.name}} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% endfor %}
{% endif %}
        <div class="col-md-2 col-sm-1"></div>

</div>

{% endblock %}
{% block jsscript %}
<script type='text/javascript'>
        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }
        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            //  var inputs = $('input, textarea, select')
            //      .not(':input[type=button], :input[type=submit], :input[type=reset]');
            //  $(inputs).each(function () {
            //      console.log(this.type);
            // });

            //  newElement = $('input').not(':input[type=button], :input[type=submit], :input[type=reset]');
            // $(newElement).each(function () {


            newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
                console.log(this.name)
                if ($(this).attr('name')) {
                    var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
                    var id = 'id_' + name;
                    $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
                }
                // var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
                // var id = 'id_' + name;
                // $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
            });
            newElement.find('label').each(function () {
                var forValue = $(this).attr('for');
                if (forValue) {
                    forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                    $(this).attr({ 'for': forValue });
                }
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            var conditionRow = $('.form-row:not(:last)');
            conditionRow.find('.btn.add-form-row')
                .removeClass('btn-success').addClass('btn-danger')
                .removeClass('add-form-row').addClass('remove-form-row')
                .html('<span class="glyphicon glyphicon-minus" aria-hidden="true"><i class="fas fa-minus"></i></span>');
            return false;
        }
        function deleteForm(prefix, btn) {
            var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1) {
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i = 0, formCount = forms.length; i < formCount; i++) {
                    $(forms.get(i)).find(':input').each(function () {
                        updateElementIndex(this, prefix, i);
                    });
                }
            }
            return false;
        }
        $(document).on('click', '.add-form-row', function (e) {
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });
        $(document).on('click', '.remove-form-row', function (e) {
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });


</script>
{% endblock %}

product/templates/product/add_product.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<br>

<div class="container">
    <div class="row">
    <div class="col-md-3 col-sm-1">

    </div>
    <div class="col-md-6 col-sm-12">
        <div class="card card-body">

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{productform.as_p}}
                <input class="btn btn-primary" type="submit" name="submit">
            </form>
        </div>
        {% if productform.errors %}
        {% for field in productform %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{field.label}} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in productform.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}


    </div>
    <div class="col-md-3 col-sm-1">

    </div>
</div>
</div>

<script>

	</script>
{% endblock %}

product/templates/product/add_type.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
        <div class="col-md-2 col-sm-1"></div>

    <div class="col-md-10 col-sm-12">
        <div class="card card-body">
            <h5 class="text-center">Create Product Type</h5>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{ productypeformset.management_form }}
            {% for form in productypeformset %}
                <div class="row form-row spacer">
                    <div class="col-2">
                    </div>
                    <div class="col-9">
                        <div class="input-group">
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            <p class="hidden">{{ form.id }}</p>
                            {{form|crispy}}
                            <div class="input-group-append">
                                <button class="btn btn-success add-form-row">+</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <br>
            <div class="row spacer">
                    <div class="col-4 offset-2">
                        <input class="btn btn-primary" type="submit" name="submit">
                    </div>
                </div>
        </form>
    </div>
    {% if productypeformset.errors %}
        {% for form in productypeformset %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{field.label}} {{field.name}} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% endfor %}
{% endif %}
        <div class="col-md-2 col-sm-1"></div>

</div>

{% endblock %}
{% block jsscript %}
<script type='text/javascript'>
        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }
        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            //  var inputs = $('input, textarea, select')
            //      .not(':input[type=button], :input[type=submit], :input[type=reset]');
            //  $(inputs).each(function () {
            //      console.log(this.type);
            // });

            //  newElement = $('input').not(':input[type=button], :input[type=submit], :input[type=reset]');
            // $(newElement).each(function () {


            newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
                console.log(this.name)
                if ($(this).attr('name')) {
                    var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
                    var id = 'id_' + name;
                    $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
                }
                // var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
                // var id = 'id_' + name;
                // $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
            });
            newElement.find('label').each(function () {
                var forValue = $(this).attr('for');
                if (forValue) {
                    forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                    $(this).attr({ 'for': forValue });
                }
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            var conditionRow = $('.form-row:not(:last)');
            conditionRow.find('.btn.add-form-row')
                .removeClass('btn-success').addClass('btn-danger')
                .removeClass('add-form-row').addClass('remove-form-row')
                .html('<span class="glyphicon glyphicon-minus" aria-hidden="true"><i class="fas fa-minus"></i></span>');
            return false;
        }
        function deleteForm(prefix, btn) {
            var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1) {
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i = 0, formCount = forms.length; i < formCount; i++) {
                    $(forms.get(i)).find(':input').each(function () {
                        updateElementIndex(this, prefix, i);
                    });
                }
            }
            return false;
        }
        $(document).on('click', '.add-form-row', function (e) {
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });
        $(document).on('click', '.remove-form-row', function (e) {
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });


</script>
{% endblock %}

product/templates/product/all_product_list.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<br>
<div class="container">
    <div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Products</h5>
        </div>
        <div class="card card-body">
            <table id="table_id" class="display text-center table">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Sell Price Normal</th>
                    <th>Sell Price Grous</th>
                    <th>Sell Price Semi-Grous</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for prod in products %}
                <tr>
                   <td>
                       <img class="card-img" style="width: 100%; height: 20vh;" src="{{prod.image.url}}" alt="{{prod.name}}">
                   </td>
                    <td>
                       {{prod.name}}
                   </td>
                    <td>
                       {{prod.category}}
                   </td>
                    <td>
                       {{prod.sellpricenormal}} DZD
                   </td>
                    <td>
                       {{prod.sellpricegrou}} DZD
                   </td>
                    <td>
                       {{prod.sellpricesemi_grou}} DZD
                   </td>
                    <td>
                        <a class="btn btn-success " href="{% url 'product:update_product' prod.id %}">Update</a>
                    </td>
                    <td>
                        <a class="btn btn-danger " href="{% url 'product:delete_product' prod.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
</div>

</div>
{% endblock %}
{% block jsscript %}
<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>
<!-- Data Table  -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>

<script type='text/javascript'>
    //Data Table init
    $(document).ready( function () {
    $('#table_id').DataTable();
} );

</script>
{% endblock %}

product/templates/product/delete.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<br>

<div class="container">
    <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="card card-body">
            <P>ARE YOU SURE YOU WANT TO DELETE {{product}}</P>
            <form action="{% url 'product:delete_product' product.id %}" method="post">

                {% csrf_token %}
                <input class="btn btn-danger" type="submit" name="Confirm">
                <a class="btn btn-warning" href="{% url 'family:family_list' %}">Cancel</a>
            </form>
        </div>
    </div>
    <div class="col-md-3">
    </div>
</div>
</div>


<script>

</script>
{% endblock %}

product/templates/product/list_product.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<br>
<div class="container">
    <div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Products</h5>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Sell Price Normal</th>
                    <th>Sell Price Grous</th>
                    <th>Sell Price Semi-Grous</th>
                </tr>

                {% for prod in products %}
                <tr>
                   <td>
                       <img class="card-img" style="width: 100%; height: 20vh;" src="{{prod.image.url}}" alt="{{prod.name}}">
                   </td>
                    <td>
                       {{prod.name}}
                   </td>
                    <td>
                       {{prod.category}}
                   </td>
                    <td>
                       {{prod.sellpricenormal}} DZD
                   </td>
                    <td>
                       {{prod.sellpricegrou}} DZD
                   </td>
                    <td>
                       {{prod.sellpricesemi_grou}} DZD
                   </td>
                    <td>
                        <a class="btn btn-success " href="{% url 'product:update_product' prod.id %}">Update</a>
                    </td>
                    <td>
                        <a class="btn btn-danger " href="{% url 'product:delete_product' prod.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

</div>
{% endblock %}