Installment/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from Installment import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    # the main ressource
    path('', include('accounts.urls', namespace='accounts')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('family/', include('family.urls', namespace='family')),
    path('category/', include('category.urls', namespace='category')),
    path('stock/', include('stock.urls', namespace='stock')),
    path('product/', include('product.urls', namespace='product')),
    path('buyorder/', include('buyorder.urls', namespace='buyorder')),
    path('sellorder/', include('sellorder.urls', namespace='sellorder')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('billingbuyorder/', include('billingbuyorder.urls', namespace='billingbuyorder')),
    path('batch/', include('batch.urls', namespace='batch')),
    path('payments/', include('payments.urls', namespace='payments')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

batch/urls.py
from django.urls import path
from . import views

app_name = 'batch'

urlpatterns = [

    path('create_batch/<str:pk>', views.create_batch, name='create_batch'),
    path('batch_list', views.batch_list, name='batch_list'),
    path('batch_pay/<str:pk>', views.batch_pay, name='batch_pay'),

]

buyorder/urls.py
from django.urls import path
from . import views

app_name = 'buyorder'

urlpatterns = [

    path('create_buyorder', views.create_buyorder, name='create_buyorder'),
    path('buyorder_list', views.buyorder_list, name='buyorder_list'),
    path('buyorder_confirmation/<str:pk>', views.buyorder_confirmation, name='buyorder_confirmation'),
    path('buyorder_pdf/<str:pk>', views.buyorder_pdf, name='buyorder_pdf'),
    path('buyorderorder_list_by_supplier/<str:pk>', views.buyorderorder_list_by_supplier, name='buyorderorder_list_by_supplier'),

]

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [

    path('create_customer_cheque/<str:pk>', views.create_customer_cheque, name='create_customer_cheque'),
    path('customer_payment_list', views.customer_payment_list, name='customer_payment_list'),

    path('create_supplier_payment/<str:pk>', views.create_supplier_payment, name='create_supplier_payment'),
    path('create_supplier_cheque/<str:pk>', views.create_supplier_cheque, name='create_supplier_cheque'),
    path('supplier_payment_list', views.supplier_payment_list, name='supplier_payment_list'),

]

supplier/urls.py
from django.urls import path
from . import views

app_name = 'supplier'

urlpatterns = [
    path('add_supplier', views.add_supplier, name='add_supplier'),
    path('supplier_list', views.supplier_list, name='supplier_list'),
    path('update_supplier/<str:pk>', views.update_supplier, name='update_supplier'),
    path('delete_supplier/<str:pk>', views.delete_supplier, name='delete_supplier'),

    path('buyorder_supplier_list', views.buyorder_supplier_list, name='buyorder_supplier_list'),

]

supplier/models.py
from django.db import models


# Create your models here.
class Supplier(models.Model):
    firstname = models.CharField(max_length=250, null=True)
    lastname = models.CharField(max_length=250, null=True)
    address = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_joined = models.DateField(null=True)
    credit = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=0.0)

    def __str__(self):
        return self.firstname + " " + self.lastname

supplier/forms.py
from django.forms import ModelForm

from supplier.models import Supplier


class SupplierForm(ModelForm):
    class Meta:
        model = Supplier

        fields = ('firstname', 'lastname', 'address', 'email', 'phone', 'credit')

supplier/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect

from supplier.forms import SupplierForm
from supplier.models import Supplier


def add_supplier(request):
    supplier_form = SupplierForm()

    if request.method == 'POST':
        supplier_form = SupplierForm(request.POST)

        if supplier_form.is_valid():
            supplier_form.save()

            return redirect('supplier:supplier_list')

    context = {
            'supplier_form': supplier_form
    }

    return render(request, 'supplier/add_supplier.html', context)


def supplier_list(request):
    suppliers = Supplier.objects.all()
    context = {
        'suppliers': suppliers
    }
    return render(request, 'supplier/list_supplier.html', context)


def buyorder_supplier_list(request):
    suppliers = Supplier.objects.all()
    context = {
        'suppliers': suppliers
    }
    return render(request, 'supplier/buyorder_list_supplier.html', context)


def update_supplier(request, pk):
    supplier = Supplier.objects.get(id=pk)
    supplier_form = SupplierForm(instance=supplier)

    if request.method == 'POST':
        supplier_form = SupplierForm(request.POST, instance=supplier)
        if supplier_form.is_valid():
            supplier_form.save()

            return redirect('supplier:supplier_list')

    context = {
        'supplier_form': supplier_form
    }
    return render(request, 'supplier/add_supplier.html', context)


def delete_supplier(request, pk):
    supplier = Supplier.objects.get(id=pk)
    context = {
        'supplier': supplier
    }
    if request.method == 'POST':
        supplier.delete()
        return redirect('supplier:supplier_list')
    return render(request, 'supplier/delete_supplier.html', context)

supplier/templates/supplier/add_supplier.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
    {{ supplier_form.media }}
</head>
<br>

<div class="row">
    <div class="col-md-2 col-sm-1"></div>
    <div class="col-md-8 col-sm-12">
        <div class="card card-body">

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{supplier_form|crispy}}
                <input class="btn btn-primary" type="submit" name="submit">
            </form>
        </div>
        {% if supplier_form.errors %}
        {% for field in supplier_form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{field.label}} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in supplier_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}
    </div>
<div class="col-md-2 col-sm-1"></div>
</div>

<script>

</script>
{% endblock %}

supplier/templates/supplier/buyorder_list_supplier.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<br>
<div class="container">
    <div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Suppliers</h5>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>City</th>

                </tr>

                {% for supplier in suppliers %}
                <tr>
                   <td>
                       {{supplier.firstname}}
                       {{supplier.lastname}}
                   </td>
                    <td>
                        <a class="btn btn-info " href="{% url 'buyorder:buyorderorder_list_by_supplier' supplier.id %}">Bill</a>
                    </td>

                </tr>

                {% endfor %}
            </table>
        </div>
    </div>
</div>

</div>
{% endblock %}

supplier/templates/supplier/delete_supplier.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<br>

<div class="container">
    <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="card card-body">
            <P>ARE YOU SURE YOU WANT TO DELETE {{supplier}}</P>
            <form action="{% url 'supplier:delete_supplier' supplier.id %}" method="post">

                {% csrf_token %}
                <input class="btn btn-danger" type="submit" name="Confirm">
                <a class="btn btn-warning" href="{% url 'supplier:supplier_list' %}">Cancel</a>
            </form>
        </div>
    </div>
    <div class="col-md-3">
    </div>
</div>
</div>


<script>

</script>
{% endblock %}

supplier/templates/supplier/list_supplier.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<br>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <h5>Customers</h5>
        </div>
        <div class="card card-body">
            <table id="table_id" class="display text-center">
                <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone</th>
                    <th>city</th>
                    <th>Credit</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for supplier in suppliers %}
                <tr>
                    <td>
                        {{supplier.firstname}}
                    </td>
                    <td>
                        {{supplier.lastname}}
                    </td>
                    <td>
                        {{supplier.phone}}
                    </td>
                    <td>
                        {{supplier.city}}
                    </td>
                    <td>
                        {{supplier.credit}}
                    </td>
                    <td>
                        <a class="btn btn-success " href="{% url 'supplier:update_supplier' supplier.id %}">Update</a>
                    </td>
                    <td>
                        <a class="btn btn-danger " href="{% url 'supplier:delete_supplier' supplier.id %}">Delete</a>
                    </td>
                    <td>
                        <a class="btn btn-primary " href="{% url 'payments:create_supplier_payment' supplier.id %}">PayDebt</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
</div>
{% endblock %}
{% block jsscript %}
<!-- custom javascript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>
<!-- Data Table  -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>

<script type='text/javascript'>
    //Data Table init
    $(document).ready( function () {
    $('#table_id').DataTable();
} );

</script>
{% endblock %}